# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply postman changes
      - run: npm i postman-to-openapi snippet-enricher-cli @redocly/cli@latest -g
      - run: p2o Chaingateway.io.postman_collection.json -f Chaingateway.io.openapi.yaml -o options.json
      - run: p2o Chaingateway.io.postman_collection.json -f Chaingateway.io.openapi.json -o options_json.json
      - run: snippet-enricher-cli --input=Chaingateway.io.openapi.json > Chaingateway.io.openapi.examples.json
      - run: redocly build-docs Chaingateway.io.openapi.examples.json --output=docs
      - run: |
          git config --global user.name "Action Bot"
          git config --global user.email "support@chaingateway.io"

          git add -A
          git commit -m "updated openapi yaml file"
          git push
      
      - uses: reggionick/s3-deploy@v3
        with:
          folder: /
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: "docs"

